### ISSUE TITLE
Lost body

### ISSUE THREAD

**Issue by MrAmericanMike** [MinecraftModDevelopment/LootableBodies#2]
So I was trying your mod on a SkyBlock type of ModPack, the problem I found is that when I died falling from a high place, into the platform I had, the body did not show up, I'm not sure if it went thru the platform and fall into the void, or if the hit sent it over the border and fall into the Void.

Will try to do some test in order to recreate, but I post it here so we can have a look at this issue. Thanks a lot.

**Comment by MrAmericanMike** [comment]
Ohhh nvm, I guess it didn't render or something? I left the area, and now the body is here o.O

http://imgur.com/GkH1lb3

Weird, I guess it was invisible until moving around for a bit.

**Comment by PitchBright** [comment]
@MrAmericanMike If this is no longer an issue, please "Close" the issue.

**Comment by MrAmericanMike** [comment]
Thanks you ;)
