### ISSUE TITLE
Will there be any official releases (per CurseForge) of this project?

### ISSUE THREAD

**Issue by Wabbit0101** [MinecraftModDevelopment/LootableBodies#8]
Hello. I know the mod's original author has retired, but there seems to be some activity here to get the mod up-to-date for at least 1.11+. However, there are no public builds to be had. Are releases planned, or is this project basically dead except for do-it-yourselfers?

**Comment by dshadowwolf** [comment]
Me and @jriwanek have been busy with Base Metals and a few other projects - there is some work in progress on getting this ported to 1.11, but it is going slowly

**Comment by Wabbit0101** [comment]
Ok, thank you for the update. I do luv Base Metals and am looking forward to that mod's rebirth (and the other baseXXX) things too!

**Comment by dshadowwolf** [comment]
Base Metals is out for 1.11 as a beta, OreSpawn (now version 3!) is also out, Modern Metals is also out for 1.11 as a beta... We've got some stuff released, some stuff in progress towards release, etc...

It's a busy time.
